#!/bin/bash 
#PBS -l nodes=1:ppn=36
#PBS -l walltime=1:00:00
#PBS -N Glyco4mer_82
#PBS -o Glyco4mer_82.o
#PBS -e Glyco4mer_82.e 
#PBS -q v100
#PBS -A hpc_mlde_gb1
#PBS -m e
#PBS -M pvalle6@lsu.edu


module load python/3.8.5-anaconda-ood


# probably need to increase the walltime for the main run 

# commented as it does not need to be recreated everytime, need to uncomment to create for the first time
# conda create --prefix /ddnA/project/jjung1/pvalle6/glycowork python=3.8
source activate /ddnA/project/jjung1/pvalle6/glycowork

#probably dont need to reinstall the same dependencies everytime, need to comment out until reinstall/recreate


#calls the script to calculate predictions
python /ddnA/project/jjung1/pvalle6/4mer_82_Glycowork.py


##